// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraineeTrackSystem.Models;

#nullable disable

namespace TraineeTrackSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TraineeTrackSystem.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Degree")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Dept_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("MinDegree")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Dept_Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100m,
                            Dept_Id = 1,
                            MinDegree = 50m,
                            Name = "ASP.NET MVC"
                        },
                        new
                        {
                            Id = 2,
                            Degree = 100m,
                            Dept_Id = 2,
                            MinDegree = 60m,
                            Name = "Networking Basics"
                        },
                        new
                        {
                            Id = 3,
                            Degree = 100m,
                            Dept_Id = 1,
                            MinDegree = 50m,
                            Name = "Database Systems"
                        });
                });

            modelBuilder.Entity("TraineeTrackSystem.Models.CrsResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Crs_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Degree")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Trainee_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Crs_Id");

                    b.HasIndex("Trainee_Id");

                    b.ToTable("CrsResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crs_Id = 1,
                            Degree = 75m,
                            Trainee_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Crs_Id = 1,
                            Degree = 40m,
                            Trainee_Id = 2
                        },
                        new
                        {
                            Id = 3,
                            Crs_Id = 2,
                            Degree = 55m,
                            Trainee_Id = 1
                        },
                        new
                        {
                            Id = 4,
                            Crs_Id = 3,
                            Degree = 90m,
                            Trainee_Id = 3
                        });
                });

            modelBuilder.Entity("TraineeTrackSystem.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manager = "Ahmed Ali",
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Manager = "Sara Mostafa",
                            Name = "Networks"
                        });
                });

            modelBuilder.Entity("TraineeTrackSystem.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dept_Id")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Dept_Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            Dept_Id = 1,
                            Image = "mona.jpg",
                            Name = "Mona Khaled",
                            Salary = 15000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            Dept_Id = 2,
                            Image = "karim.jpg",
                            Name = "Karim Adel",
                            Salary = 18000m
                        });
                });

            modelBuilder.Entity("TraineeTrackSystem.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dept_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Dept_Id");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tanta",
                            Dept_Id = 1,
                            Grade = 0m,
                            Image = "youssef.jpg",
                            Name = "Youssef Hassan"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Mansoura",
                            Dept_Id = 2,
                            Grade = 0m,
                            Image = "mariam.jpg",
                            Name = "Mariam Adel"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Cairo",
                            Dept_Id = 1,
                            Grade = 0m,
                            Image = "omar.jpg",
                            Name = "Omar Saeed"
                        });
                });

            modelBuilder.Entity("TraineeTrackSystem.Models.Course", b =>
                {
                    b.HasOne("TraineeTrackSystem.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("Dept_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TraineeTrackSystem.Models.CrsResult", b =>
                {
                    b.HasOne("TraineeTrackSystem.Models.Course", "Course")
                        .WithMany("CrsResults")
                        .HasForeignKey("Crs_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TraineeTrackSystem.Models.Trainee", "Trainee")
                        .WithMany("CrsResults")
                        .HasForeignKey("Trainee_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TraineeTrackSystem.Models.Instructor", b =>
                {
                    b.HasOne("TraineeTrackSystem.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("Dept_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TraineeTrackSystem.Models.Trainee", b =>
                {
                    b.HasOne("TraineeTrackSystem.Models.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("Dept_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TraineeTrackSystem.Models.Course", b =>
                {
                    b.Navigation("CrsResults");
                });

            modelBuilder.Entity("TraineeTrackSystem.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("TraineeTrackSystem.Models.Trainee", b =>
                {
                    b.Navigation("CrsResults");
                });
#pragma warning restore 612, 618
        }
    }
}
